language: julia
os:
  - osx
  - linux
julia:
  - release
  - nightly
script:
#  - if [ `uname` == "Linux" ]; then sudo apt-add-repository ppa:kalakris/cmake -y; fi
#  - if [ `uname` == "Linux" ]; then sudo apt-get update -qq -y; fi
#  - if [ `uname` == "Linux" ]; then sudo apt-get install -y cmake; fi
  - if [ `uname` == "Linux" ]; then
    wget http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.tar.gz;
    tar -xzf cmake-3.2.1-Linux-x86_64.tar.gz;
    sudo cp -fR cmake-3.2.1-Linux-x86_64/* /usr;
    export PATH=`pwd`/cmake-3.2.1-Linux-x86_64/bin:$PATH; fi
  - which cmake
  - cmake --version
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone("https://github.com/optimizers/NLP.jl.git")'
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("ampl"); Pkg.test("ampl"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("ampl")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

