language: julia

os:
  - osx
  - linux

julia:
  - release

before_install:
  - unset DYLD_LIBRARY_PATH
  - if [ `uname` == "Linux" ]; then sudo apt-get install -y cmake; fi
  - if [ `uname` == "Darwin" ]; then brew --config; brew update; fi

install:
  # Install ASL.
  - if [ `uname` == "Darwin" ]; then brew tap homebrew/science; brew install asl; fi
  - julia -e 'versioninfo()'
  - julia -E 'Pkg.clone("https://github.com/optimizers/NLP.jl.git")'
  - julia -E 'Pkg.clone(pwd())';
  - julia -E 'Pkg.build("ampl");'
  - julia -E 'using BinDeps; BinDeps.debug("ampl")'

script:
  - julia --check-bounds=yes -e 'Pkg.test("ampl"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("ampl")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

