language: julia
os:
  - osx
  - linux
julia:
  - release
  - nightly
script:
  - if [ `uname` == "Linux" ]; then
    wget --no-check-certificate http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.tar.gz;
    tar -xzf cmake-3.2.1-Linux-x86_64.tar.gz;
    sudo cp -fR cmake-3.2.1-Linux-x86_64/* /usr;
    export PATH=`pwd`/cmake-3.2.1-Linux-x86_64/bin:$PATH; fi
  - which cmake
  - cmake --version
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone("https://github.com/JuliaOptimizers/NLPModels.jl.git"); Pkg.checkout("NLPModels", "develop"); Pkg.build("NLPModels")'
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("AmplNLReader"); Pkg.test("AmplNLReader"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("AmplNLReader")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
