language: julia
# Homebrew no longer bottles for OSX 10.9; request 10.11
matrix:
  include:
    - os: linux
      julia: 0.4
    - os: linux
      julia: 0.5
    - os: linux
      julia: 0.6
    - os: osx
      julia: 0.4
      osx_image: xcode7.3
    - os: osx
      julia: 0.5
      osx_image: xcode7.3
    - os: osx
      julia: 0.6
      osx_image: xcode7.3
addons:
  apt_packages:
    - gfortran
branches:
  only:
    - master
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    julia -E 'Pkg.clone("https://github.com/dpo/Linuxbrew.jl.git"); Pkg.build("Linuxbrew"); using Linuxbrew; Linuxbrew.add("patchelf")'; fi
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd())'
  - julia --check-bounds=yes -e 'Pkg.build("AmplNLReader"); Pkg.test("AmplNLReader"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("AmplNLReader")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
